<a href="https://colab.research.google.com/github/zs-x/TensorFlowNotes/blob/main/fCC_IntroToTF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
str = tf.Variable("str", tf.string)
int = tf.Variable(123, tf.int16)
float = tf.Variable(123.123, tf.float64)
bool = tf.Variable(True, tf.bool)
complex = tf.Variable(123 + 456j, tf.complex64)
string_array = tf.Variable(["str1", "str2", "str3"], tf.string)
int_array = tf.Variable([1, 2, 3], tf.int16)
float_array = tf.Variable([1.1, 2.2, 3.3], tf.float64)
bool_array = tf.Variable([True, False, True], tf.bool)
complex_array = tf.Variable([123 + 456j,
                             123 + 456j,
                             123 + 456j], tf.complex64)

In [ ]:
rank_1 = tf.Variable([1, 2, 3], tf.int16)
rank_2 = tf.Variable([[1, 2, 3], [4, 5, 6]], tf.int16)

In [ ]:
tf.rank(int)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tf.rank(rank_1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(rank_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
rank_1.shape

TensorShape([3])

In [ ]:
rank_2.shape

TensorShape([2, 3])

In [ ]:
# changing shape

In [ ]:
tensor1 = tf.ones([1, 2, 3])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tensor2 = tf.reshape(tensor1, [2, 3, 1]) # 2 outside lists, 3 lists inside, 1 item inside
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place
# so in this case it will be [3, 2]
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
t = tf.zeros([5, 5, 5, 5])
t = tf.reshape(t, [625])
t

<tf.Tensor: shape=(625,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0